### ISSUE TITLE
z/OSMF list of datasets fails for archived datasets

### ISSUE THREAD

**Issue by VitekVlcek-Broadcom** [zowe/data-sets#127]
**Describe the bug**
This is a z/OSMF bug of `/zosmf/restfiles/ds?dslevel=TSARB` REST
When the HLQ contains an archived dataset and REST call has HTTP header `X-IBM-Attributes:base` z/OSMF fails to retrieve list of all datasets. 
**Note**: Without `X-IBM-Attributes:base` call finishes OK.

**To Reproduce**
1) find a HLQ that has alteast one archived dataset
2) issue `/zosmf/restfiles/ds?dslevel=TSARB`  with `X-CSRF-ZOSMF-HEADER:aa`,  `X-IBM-Attributes:base` against z/OSMF
3) z/OSMF response  `500 Internal Server Error`
```json 
 {
    "rc": 4,
    "reason": 3,
    "details":["ARC1020I DFSMSHSM IS RECALLING FROM TAPE DSN=TSARB.BACKUP.ASNA21.HDT0.D160323, YOU MAY CONTINUE THE RECALL IN THE BACKGROUND AND FREE YOUR TSO SESSION BY PRESSING THE ATTENTION KEY                    ",
    "ARC1020I DFSMSHSM IS RECALLING FROM TAPE DSN=TSARB.BACKUP.VOLTAGE.HDT0.D150120, YOU MAY CONTINUE THE RECALL IN THE BACKGROUND AND FREE YOUR TSO SESSION BY PRESSING THE ATTENTION KEY                   ",
    "ARC1020I DFSMSHSM IS RECALLING FROM TAPE DSN=TSARB.BACKUP.ZSECURE.HDT0.D150128, YOU MAY CONTINUE THE RECALL IN THE BACKGROUND AND FREE YOUR TSO SESSION BY PRESSING THE ATTENTION KEY                   ",
    "IDI0034I Fault analysis skipped due to: EXCLUDE option specification (FAST)",
    "* ISPF Subtask abend *        ",
    "IKJ56641I ISPSTART ENDED DUE TO ERROR+               ",
    "READY "],
    "category": 2,
    "message": "ServletDispatcher failed - received TSO Prompt when expecting TsoServletResponse"
}
```

Additional debug information:
- [20191009_TSO_output1.txt](https://github.com/zowe/data-sets/files/3718696/20191009_TSO_output1.txt)
- [20191009_TSO_output2.txt](https://github.com/zowe/data-sets/files/3718698/20191009_TSO_output2.txt)

**Expected behavior**
You get one or many entries in json response regardless a data-set is archived 
```json
	 {
		"items": [
			{
				"dsname": "TSARB.ZOSMFRAC",
				"blksz": "6233",
				"catnm": "UCAT.HDPLEXT0.TSO",
				"cdate": "2014/07/29",
				"dev": "3390",
				"dsorg": "PS-E",
				"edate": "***None***",
				"extx": "1",
				"lrecl": "256",
				"migr": "NO",
				"mvol": "Y",
				"ovf": "NO",
				"rdate": "2019/10/08",
				"recfm": "VB",
				"sizex": "15",
				"spacu": "CYLINDERS",
				"used": "6",
				"vol": "TSTT00",
				"vols": "TSTT00,*     ,*     ,*     *"
			}
		],
		"returnedRows": 1,
		"JSONversion": 1
	}
```

**Additional context**
Same behavior happens with `CA DISK` product with this message

```json
HTTP/1.1 500 Internal Server Error
Connection: Close
Content-Language: en-US
Content-Type: application/json;charset=UTF-8
Date: Fri, 11 Oct 2019 16:32:21 GMT
Transfer-Encoding: chunked
X-IBM-Txid: tx0000000000087B16

{
    "category": 2,
    "details": [
        "DMS2987 DATA SET CATALOGED TO CA DISK PSEUDO-VOLUME ARCIVE                                                              ",
        "DMS2987 CA DISK HAS ARCHIVED VLCVI01.A.SMPLTS                                                                           ",
        "   ",
        "DMS2971 DO YOU WANT TO RESTORE THE DATA SET? (Y/N)"
    ],
    "message": "ServletDispatcher failed - received TSO Prompt when expecting TsoServletResponse",
    "rc": 4,
    "reason": 3
}
```

**Comment by VitekVlcek-Broadcom** [comment]
Not sure if this changes anything, customer mentioned that datasets on TSARB HLQ got eventually recalled.

**Comment by VitekVlcek-Broadcom** [comment]
Based on suggestion I played with `X-IBM-Migrated-Recall` header, I tried all 3 options 
 - error
 - wait
 - nowait

Without any success. It when `X-IBM-Attributes:base` is present call fails. Without `X-IBM-Attributes:base` call succeeds.

**Comment by leofang-zOSMF** [comment]
Currently X-IBM-Migrated-Recall is just for list PDS members, retrieve a data set or PDS members, write data to a data set or members and data set/pds member utility.
Another word, X-IBM-Migrated-Recall can not support List data set for now. I will investigate it ASAP.

**Comment by leofang-zOSMF** [comment]
@VitekVlcek-Broadcom , may I ask which release you are using, V2R2 or V2R3 or V2R4?

**Comment by leofang-zOSMF** [comment]
And what's your latest PTF for component 5655S28RF? 
Or could you please give me your PTF list for z/OSMF?

**Comment by VitekVlcek-Broadcom** [comment]
I don't have access to SMPE but here is a z/OSMF response
```yaml
zosmf_port:         1443
zosmf_saf_realm:    SAFRealm
zos_version:        04.26.00
zosmf_full_version: 26.0
api_version:        1

z/OSMF Plug-ins that are installed on 'usilca32.lvn.broadcom.net':
-
  pluginVersion:     HSMA230;PH12708P;2019-06-20T04:29:14
  pluginDefaultName: z/OS Operator Consoles
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA234;PH15703P;2019-08-27T14:56:58
  pluginDefaultName: Software Deployment
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA230;PI96931P;2018-05-22T06:55:26
  pluginDefaultName: Variables
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA235;PH11149P;2019-05-16T02:14:12
  pluginDefaultName: IncidentLog
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA237;PH12733P;2019-06-12T05:58:36
  pluginDefaultName: Workflow
  pluginStatus:      ACTIVE
-
  pluginVersion:     HQX77B0;PI85015;2017-08-14T21:47:00
  pluginDefaultName: IBM SDSF
-
  pluginVersion:     HSMA23A;PH14555;2019-10-03T04:20:37
  pluginDefaultName: Network Configuration Assistant
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA23A;PH14624;2019-08-21T03:06:25
  pluginDefaultName: IBM zERT Network Analyzer
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA230;PH10944P;2019-05-28T02:03:52
  pluginDefaultName: Sysplex Management
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA231;PH08534P;2019-03-27T08:54:23
  pluginDefaultName: ISPF
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA230;PI96730P;2019-01-17T09:21:36
  pluginDefaultName: Import Manager
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA232;PH06809P;2019-02-28T05:14:30
  pluginDefaultName: ResourceMonitoring
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA233;PH08950P;2019-03-13T05:42:52
  pluginDefaultName: WorkloadManagement
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA236;PH09942P;2019-03-27T07:50:00
  pluginDefaultName: Capacity Provisioning
  pluginStatus:      ACTIVE
-
  pluginVersion:     HSMA230;PH12793P;2019-07-16T06:59:19
  pluginDefaultName: Cloud Provisioning
  pluginStatus:      ACTIVE
```
